name: Scheduled Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间的00:00触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run auto.py and commit changes
        run: |
          python auto.py
          git config --local user.email "2654317003@qq.com"
          git config --local user.name "jsiptv"
          git add .
          git commit -m "Automated commit from GitHub Action"
          git push origin main
