name: Merge Documents

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜零点触发运行

jobs:
  merge_documents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and merge documents
        run: |
          # 定义要下载的文档地址列表
          document_urls = [
             'https://git.iptv-cn.tk/https://raw.githubusercontent.com/jsiptv/jsiptv.github.io/main/TV/v6.txt',
             'https://git.iptv-cn.tk/https://raw.githubusercontent.com/jsiptv/tv/main/itvlist.txt'
          ]

         # 创建一个空字符串，用于保存所有文档内容
          all_document_content = ''

          # 循环遍历文档地址列表，逐个获取文档内容并拼接到 all_document_content 中
          for url in document_urls:
              curl -L "$url" >> all.txt
              all_document_content += document_content + '\n'

          # 将合并后的文档内容写入到 all.txt 文件中
          echo "$all_document_content" > all.txt

         - name: Commit changes
        run: |
          git config --global user.email '2654317003@qq.com'
          git config --global user.name 'jsiptv'
          git add .
          git commit -m "Merge documents" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


