ame: Scheduled Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间的00:00触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run auto.py and copy files to main branch
        run: |
          python auto.py
          cp all.txt $GITHUB_WORKSPACE/all.txt
          cd $GITHUB_WORKSPACE
          git checkout main
          git add all.txt
          git commit -m "Add generated file"
          git push origin main
